name: Kubernetes Deploy CI/CD

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Setup Kubectl
      uses: azure/setup-kubectl@v4


    - name: Configure Kubernetes
      run: |
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml


    - name: Verify Deployment
      run: |
        kubectl get pods -n docker-app
        kubectl get service -n docker-app
